import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  const data = await req.json();
  const { text } = data;

  // Placeholder response (fake AI output)
  const response = {
    linkedin: "This is a LinkedIn post generated by API",
    instagram: "Short Instagram caption from API",
    carousel: ["Slide 1: Hook", "Slide 2: Point", "Slide 3: CTA"],
  };

  return NextResponse.json(response);
}
